services:
  # server:
  #   build: .
  #   hostname: server
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - PGHOST=db
  #     - PGPASSWORD=1234
  #     - PGUSER=postgres
  #     - PGDATABASE=postgres
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - REDIS_PASSWORD=1234
  #     - SESSION_SECRET=sus
  #     - NODE_ENV=dev
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     redis-stack:
  #       condition: service_healthy

  redis-stack:
    image: redis/redis-stack
    hostname: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      REDIS_ARGS: "--requirepass 1234"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a 1234 ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  db:
    image: postgres:18
    hostname: db
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./configs/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pg_admin:
    image: dpage/pgadmin4
    container_name: pg_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=ahmed.hesham.farag@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
    ports:
      - 81:80
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    hostname: prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      # - ./rules:/rules
      # - ./data:/prometheus/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
    

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - '3000:3000'

  alloy:
    image: grafana/alloy
    hostname: alloy
    restart: unless-stopped
    volumes:
      - ./configs/alloy:/etc/alloy/
      # - /home/ahmed/.kube/config:/config
    ports:
      - 12345:12345
    command: >
      run
      --server.http.listen-addr=0.0.0.0:12345
      --storage.path=/var/lib/alloy/data
      /etc/alloy

  loki:
    image: grafana/loki
    hostname: loki
    restart: unless-stopped
    ports:
      - 3100:3100

  
  # tempo:
  #   image: grafana/tempo
  #   restart: unless-stopped
  #   hostname: tempo
  #   ports:
  #     - 3200:3200
  #     - 4318:4318
  #     - 9095:9095
  #   volumes:
  #     - ./configs/tempo.yaml:/etc/tempo.yaml
  #   command:
  #     - '-target=all'
  #     - '-config.file=/etc/tempo.yaml'