services:
  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      REDIS_ARGS: "--requirepass 1234"
    restart: unless-stopped

  db:
    image: postgres:18
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    restart: unless-stopped
  pg_admin:
    image: dpage/pgadmin4:latest
    container_name: pg_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=ahmed.hesham.farag@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1234
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
    ports:
      - 81:80
    restart: unless-stopped

  prometheus:
    image: "prom/prometheus:latest"
    hostname: prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      # - ./rules:/rules
      # - ./data:/prometheus/data
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    ports:
      - '3000:3000'