scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- job_name: url_shortener
  static_configs:
  - targets:
    - server:8080

# rule_files:
#   - "/rules/myrules.yml"